services:
  - type: web
    name: crm-app
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/CRM-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql-canquaca.alwaysdata.net:3306/canquaca_crm
      - key: SPRING_DATASOURCE_USERNAME
        value: canquaca
      - key: SPRING_DATASOURCE_PASSWORD
        value: Chutho@2004
      - key: JAVA_VERSION
        value: 8
